# 服务相关
server:
  port: 8080
  name: ivay-app

# 数据库配置
dataSource:
  master: true
  slave: false

spring:
  profiles:
    # 多模块使用include取代active
    include: dev, comDev, dbDev
#    include: test, comTest, dbTest
#    include: prod, comProd, dbProd
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false

token:
  expire:
    seconds: 259200
  jwtSecret: (JUN:)_$^11244^%$_(XING:)_@@++--(KE:)_++++_.sds_(JI:)
  
#短信验证码失效时间
verifycode:
    effectiveTime: 120000

# 是否对敏感信息解密
needDecrypt: false

