spring:
  redis:
    host: localhost
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
#    database: 0
#    password: ivay_test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+7

files:
  path: ${file-path:/data/files}

swagger:
  enbale: true

# 定时器
timer:
  # 逾期费用
  overdueFee: 0 0 1 1/1 * ?
  firebaseNotice: 0 26 19 1/1 * ?

# 借款url
#baokim
api_transfer_url: http://13.250.110.81:9095/Sandbox/FirmBanking
api_partner_code: FINTECH
api_request_id_prefix: FINTECHBK
#ebay
ebay_api_transfer_url: https://chihoepay.megacard.vn:3669/Sandbox/PartnerMoneyTransfer
ebay_api_partner_code: PARTNERTEST01
ebay_api_request_id_prefix: PARTNERTEST01EP

# 还款url
api_collection_url: http://13.250.110.81:8085/Sandbox/Collection
# 发送短信url
api_paasoo_url: https://api.paasoo.com/json?key={key}&secret={secret}&from={from}&to={to}&text={text}
api_paasoo_key: nzwzxcuv
api_paasoo_secret: 2aandS4r
# 发送短信url
api_vmgmedia_url: http://brandsms.vn:8018/VMGAPI.asmx
api_alias: VMGtest
api_authenticate_user: vmgtest1
api_authenticate_pass: vmG@123b
# 风控授权rl
risk_control_url: http://localhost:8081/audit/queryAuditQualification?userGid={userGid}&flag={flag}
# 风控提额url
update_credit_limit_url: http://localhost:8081/audit/updateCreditLimit?userGid={userGid}
# 授信自动审计url
auto_audit_url: http://localhost:8081/audit/autoAudit?userGid={userGid}


# 前端错误日志路径：
errorInfo.path: /data/errorInfo/

#firebase SDK路径：
firebase_sdk_url: /usr/firebase/ovay-release-firebase-adminsdk-3evco-943d00a328.json
#firebase ovay项目地址：
firebase_project_url: https://ovay-release.firebaseio.com