# 服务相关
server:
  port: 8080
  name: ivay-app

# 数据库配置
dataSource:
  master: true
  slave: false

spring:
  profiles:
    # 多模块使用include取代active
    include: dev, comDev, dbDev
#    include: test, comTest, dbTest
#    include: prod, comProd, dbProd
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true

token:
  expire:
    seconds: 1800
  jwtSecret: (JUN:)_$^11244^%$_(XING:)_@@++--(KE:)_++++_.sds_(JI:)

# 是否对敏感信息解密
needDecrypt: false

