spring:
  redis:
    host: localhost
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



files:
  path: ${file-path:c:/files}

swagger:
  enbale: true

# 定时器
timer:
  # 逾期费用
  overdueFee: 0 0 1 1/1 * ?
  firebaseExpireNotice: 0 23 11 * * ?   #对当天逾期的用户发送一次
  firebaseOverDueNotice: 0 0 9 1/3 * ?  #每3天发送一次
  autoCreateVA: 0 30 0-23 * * ?  #每小时创建一次
  transferTimeout: 0 10 0-23 * * ?

# 借款url
#baokim
api_transfer_url: http://13.250.110.81:9095/Sandbox/FirmBanking
api_partner_code: FINTECH
#ebay
ebay_api_transfer_url: https://chihoepay.megacard.vn:3669/Sandbox/PartnerMoneyTransfer
ebay_api_partner_code: PARTNERTEST01

# 还款url
#baokim
api_collection_url: http://13.250.110.81:8085/Sandbox/Collection
#ebay
ebay_api_collection_url: http://42.113.207.131:10002/ApiResf_VirtualAccount/services/registerVA
ebay_api_merchant_code: VAP001
ebay_api_keyMahoa: 31feae316de0a42520ef5ec4
#虚拟账号有效期：以年为单位
ebay_api_effective_year: 5
#ebay还款回调接口公钥路径
ebay_api_notice_publickey: C:/usr/ebay_notice_key/ebay_notice_public_key.pem

# 风控授权url
risk_control_url: http://localhost:8081/audit/queryAuditQualification?userGid={userGid}&flag={flag}
# 还款成功的后置处理url, 提额、增加白名单
repayment_success_post_handle_url: http://localhost:8081/audit/repaymentSuccessPostHandle?userGid={userGid}
# 授信自动审计url
auto_audit_url: http://localhost:8081/audit/autoAudit?userGid={userGid}


# 前端错误日志路径：
errorInfo.path: /data/errorInfo/
