spring:
  redis:
    host: 10.53.138.16
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
#    database: 1
#    password: ivayRedisB038

files:
  path: ${file-path:/data/files}

swagger:
  enbale: false

# 定时器
timer:
  # 逾期费用
  overdueFee: 0 0 1 1/1 * ?

# 借款url
api_transfer_url: http://210.245.83.82:9095/Golive/FirmBanking
api_partner_code: VINFINTECH
api_request_id_prefix: VINFINTECHBK
# 还款url
api_collection_url: http://210.245.80.27:9092/Golive/Collection
# 发送短信url
api_paasoo_url: https://api.paasoo.com/json?key={key}&secret={secret}&from={from}&to={to}&text={text}
api_paasoo_key: nzwzxcuv
api_paasoo_secret: 2aandS4r
# 发送短信url
api_vmgmedia_url: http://brandsms.vn:8018/VMGAPI.asmx
api_alias: VMGtest
api_authenticate_user: vmgtest1
api_authenticate_pass: vmG@123b
# 风控授权url
risk_control_url: http://10.53.104.178:8081/audit/queryAuditQualification?userGid={userGid}&flag={flag}
# 风控提额url
update_credit_limit_url: http://10.53.104.178:8081/audit/updateCreditLimit?userGid={userGid}
# 授信自动审计url
auto_audit_url: http://10.53.104.178:8081/audit/autoAudit?userGid={userGid}


# 前端错误日志路径：
errorInfo.path: /data/errorInfo/