spring:
  redis:
    host: localhost
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
files:
  path: ${file-path:c:/files}

swagger:
  enbale: true

# 定时器
timer:
  # 逾期费用
  overdueFee: 0 0 0 1/1 * ?

# 借款url
api_transfer_url: http://13.250.110.81:9095/Sandbox/FirmBanking
api_partner_code: FINTECH
api_request_id_prefix: FINTECHBK
# 还款url
api_collection_url: http://210.245.80.27:9092/Golive/Collection
# 发送短信url
api_paasoo_url: https://api.paasoo.com/json?key={key}&secret={secret}&from={from}&to={to}&text={text}
api_paasoo_key: nzwzxcuv
api_paasoo_secret: 2aandS4r
# 发送短信url
api_vmgmedia_url: http://brandsms.vn:8018/VMGAPI.asmx
api_alias: VMGtest
api_authenticate_user: vmgtest1
api_authenticate_pass: vmG@123b
# 风控授权rl
risk_control_url: http://localhost:8081/audit/queryAuditQualification?userGid={userGid}&flag={flag}
# 风控提额url
update_credit_limit_url: http://localhost:8081/audit/updateCreditLimit?userGid={userGid}
# 公私钥路径
keyfilepath: /usr/key/dev/

