files:
  path: ${file-path:c:/files}
log:
  level:
    root: info
    my: debug
  file: /logs/admin-server.log
  maxsize: 30MB

swagger:
  enbale: true

# 定时器
timer:
  # 逾期费用
  overdueFee: 0 0 0 1/1 * ?

api_transfer_url: http://13.250.110.81:9095/Sandbox/FirmBanking
api_collection_url: http://13.250.110.81:8085/Sandbox/Collection
api_paasoo_url: https://api.paasoo.com/json?key={key}&secret={secret}&from={from}&to={to}&text={text}
api_paasoo_key: nzwzxcuv
api_paasoo_secret: 2aandS4r
api_vmgmedia_url: http://brandsms.vn:8018/VMGAPI.asmx
api_alias: VMGtest
api_authenticate_user: vmgtest1
api_authenticate_pass: vmG@123b
risk_control_url: http://localhost:8081/audit/queryAuditQualification?userGid={userGid}&flag={flag}
keyfilepath: /usr/