package plausibcheck.address

import com.ivay.ivay_repository.dto.Address;
import com.ivay.ivay_repository.dto.AddressCheckResult;

rule "年龄校验"
when
    address : Address( year >= 18, year <=50 )
    checkResult : AddressCheckResult()     
then
    checkResult.setYearResult(true);
    System.out.println("年龄:"+ address.getYear() + "校验通过!");
end

rule "姓名编辑距离校验"
when
    address : Address( nameDis <=1 )
    checkResult : AddressCheckResult()     
then
    checkResult.setNameDisResult(true);
    System.out.println("规则中打印日志：姓名编辑距离校验通过!");
end

rule "联系人数量校验"
when
    address : Address( contactNum > 10 && contactMaxNum > 10 )
    checkResult : AddressCheckResult()     
then
    checkResult.setContactNumResult(true);
    System.out.println("规则中打印日志：联系人数量校验通过!");
end

rule "设备一个月内注册账户数校验"
when
    address : Address( macNum <=1 )
    checkResult : AddressCheckResult()     
then
    checkResult.setMacNumResult(true);
    System.out.println("规则中打印日志：同一手机设备一个月内注册账户数校验通过!");
end

rule "近一个月同一gps(精确到10m)注册用户数校验"
when
    address : Address( gpsNum <=1 )
    checkResult : AddressCheckResult()     
then
    checkResult.setGpsNumResult(true);
    System.out.println("规则中打印日志：近一个月同一gps(精确到10m)注册用户数校验通过!");
end

