# 日志配置文件
logging:
  config: classpath:logback-ivay.xml

logfile:
  # 日志存放路径
  path: /data/logs/
  totalSizeCap: 10GB

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true

# 自定义配置
# baokim接口私钥存放路径
keyfilepath: /usr/key/test/
# baokim接口参数
api_request_id_prefix: FINTECHBK
# ebay接口参数
ebay_api_request_id_prefix: PARTNERTEST01EP

