# 日志配置文件
logging:
  config: classpath:logback-ivay.xml

logfile:
  # 日志存放路径
  path: /data/logs/
  totalSizeCap: 10GB

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    use-code-as-default-message: true

# 自定义配置
# baokim接口私钥存放路径
keyfilepath: /usr/prod/
# baokim接口参数
api_request_id_prefix: VINFINTECHBK
# ebay接口参数
ebay_api_request_id_prefix:

#firebase SDK路径：
firebase_sdk_url: /usr/firebase/ovay-release-firebase-adminsdk-3evco-943d00a328.json
#firebase ovay项目地址：
firebase_project_url: https://ovay-release.firebaseio.com

# 发送短信url
api_paasoo_url: https://api.paasoo.com/json?key={key}&secret={secret}&from={from}&to={to}&text={text}
#发送短信验证码的key和secret
api_paasoo_code_key: nzwzxcuv
api_paasoo_code_secret: 2aandS4r
#发送通知短信的key和secret
api_paasoo_notice_key: cftpyvnv
api_paasoo_notice_secret: cftpyvnv

# 发送短信url-fpt
api_fpt_grant_type: client_credentials
api_fpt_client_id: b06e9A9bB0d984d14D37b957A33D7597c37a9c44
api_fpt_client_secret: f5fC98c0c6526b0bd80c283738f40ba48884e7b7fda469b26B98a38bB432f30ccaA3233c
api_fpt_scope: send_brandname_otp
api_fpt_accesstoken_url: http://app.sms.fpt.net/oauth2/token
api_fpt_sendmsg_url: http://app.sms.fpt.net/api/push-brandname-otp
api_fpt_brandName: FTI