
mybatis:
  type-aliases-package: com.ivay.ivay_manage.model
  mapper-locations: classpath:/mybatis-mappers/*, classpath:/risk/*
  configuration:
    mapUnderscoreToCamelCase: true
files:
  path: ${file-path:c:/files}
logging:
  config: classpath:logback-admin.xml
token:
  expire:
    seconds: 7200
  jwtSecret: (XX:)_$^11244^%$_(XX:)_@@++--(XX:)_++++_.sds_(XX:)
server:
  port: 8081