spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+7
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: 10.53.138.16
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    database: 0
    #password: ivayRedisB038
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false
files:
  path: ${file-path:/data/files}

token:
  expire:
    seconds: 7200
  jwtSecret: (XX:)_$^11244^%$_(XX:)_@@++--(XX:)_++++_.sds_(XX:)

xAppEvents_event_url: http://10.53.138.16:8080/star/xAppEvents/save

# 定时器
timer:
  # 逾期订单生成催收任务
  overdueOrder: 0 10 0 1/1 * ?