# 服务相关
server:
  port: 8081
  name: ivay-manage

# 数据库配置
dataSource:
  master: true
  slave: true

#短信通知失效时间(单位：s)
noticemsg:
  effectiveTime: 259200

verifycode:
  #发送短信验证码的间隔时间(约2min，单位ms)
  effectiveTime: 120001
  #短信验证码有效时间(10min，单位ms)
  validTime: 600000

info:
  status: ok

management:
  endpoint:
    info:
      enabled: true
  info:
    git:
      enabled: true
      mode: full

spring:
  profiles:
    # 多模块使用include取代active
#    include: dev, comDev, dbLoc
#    include: dev, comDev, dbDev
    include: test, comTest, dbTest
#    include: prod, comProd, dbProd
