files:
  path: ${file-path:/data/files}
logging:
  config: classpath:logback-admin.xml
token:
  expire:
    seconds: 7200
  jwtSecret: (XX:)_$^11244^%$_(XX:)_@@++--(XX:)_++++_.sds_(XX:)
server:
  port: 8081