# 服务相关
server:
  port: 8081
  name: ivay-manage

# 数据库配置
dataSource:
  master: true
  slave: true

#短信通知失效时间
noticemsg:
  effectiveTime: 259200

spring:
  profiles:
    # 多模块使用include取代active
#    include: dev, comDev, dbLoc
    include: dev, comDev, dbDev
#    include: test, comTest, dbTest
#    include: prod, comProd, dbProd

