# app事件上报
xAppEvents_event_url: http://localhost:8080/star/xAppEvents/save

spring:
  redis:
    host: localhost
    port: 6379
    # 连接等待时间（ms）
    timeout: 5000
    lettuce:
      pool:
        # 空闲连接数
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
files:
  path: ${file-path:c:/files}

token:
  expire:
    seconds: 7200
  jwtSecret: (XX:)_$^11244^%$_(XX:)_@@++--(XX:)_++++_.sds_(XX:)

# 定时器
timer:
  # 逾期订单生成催收任务 每天02:10触发
  overdueOrder: 0 10 2 1/1 * ?
  # 催收报表统计 每天02:20触发
  calculateCollection: 0 20 2 1/1 * ?
